# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do

  ensure_git_status_clean    
# Очистка проекта
    xcclean(
      scheme: "SpaceXRockets",
      workspace: "SpaceXRockets.xcworkspace"
    )

# Обновление библиотек
    cocoapods(
      use_bundle_exec: false
    )

    # Запуск тестов

    run_tests

# Делаем скриншоты
capture_ios_screenshots



    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :project_deploy do

    increment_build_number


    gym(
      scheme: "SpaceXRockets",
      configuration: "Debug",
      export_method: "development",
      include_symbols: "true",
      include_bitcode: "true",
      silent: false
    )

  end
end
